stages:
  - test
  - deploy

variables:
  DOCKER_REGISTRY: 471112647960.dkr.ecr.us-east-2.amazonaws.com/my-api1
  IMAGE_TAG: $CI_COMMIT_SHA
  KUBECONFIG_PASSPHRASE: "Admin123456"

updating-env-file:
  stage: test
  image:
    name: docker:latest
  services:
    - docker:dind
  before_script:
    - echo "DATABASE_URL=\"mysql://admin:Admin123456@database-api.cjyuskquoc67.us-east-2.rds.amazonaws.com:3306/nestjs_api"\" >> ./app/.env
    - cat ./app/.env
    - apk add --no-cache curl jq python3 py3-pip
    - pip install awscli --break-system-packages
    - aws ecr get-login-password | docker login --username AWS --password-stdin $DOCKER_REGISTRY

    # - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    # - unzip awscliv2.zip
    # - ./aws/install

    # - apk add --no-cache curl jq python3 py3-pip
    # - python -m pip install awscli --break-system-packages

    - aws --version
    # - docker info
    # - docker --version
  script:
    # - aws eks list-clusters
    # - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin $DOCKER_REGISTRY
    - docker build -t $DOCKER_REGISTRY:$IMAGE_TAG -f ./app/Dockerfile "app"
    - docker push $DOCKER_REGISTRY:$IMAGE_TAG

# veryfing-env-file:
#   stage: test
#   script:
#     - cat ./app/.env

# listing-dir:
#   image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
#   script:
#     - aws eks list-clusters

# veryfing-env-file:
#   script:
#     - cat ./app/.env

kubernetes:
  image:
    name: bitnami/kubectl:1.14
    entrypoint: [""]
  script:
    #- kubectl get pods
    - chmod +x ./decrypt_secret.sh
    - ./decrypt_secret.sh
    - cat $HOME/secrets/kubeconfig
# deploy-prod:
#   stage: deploy
#   script:
#     - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
#   environment: production
