stages:
  - test

aws-login:
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  script:
    - aws eks list-clusters

updating-env-file:
  stage: test
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  variables:
    ECR_URL: 471112647960.dkr.ecr.us-east-2.amazonaws.com/my-api1
    IMAGE_TAG: 0.0.10
  script:
    - echo "DATABASE_URL=\"mysql://admin:Admin123456@database-api.cjyuskquoc67.us-east-2.rds.amazonaws.com:3306/nestjs_api"\" >> ./app/.env
    - cat ./app/.env
    - aws eks list-clusters
    - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin $ECR_URL
    - docker build -t $ECR_URL:$IMAGE_TAG -f ./app/Dockerfile "app"
    # - docker push $ECR_URL:$IMAGE_TAG

veryfing-env-file:
  stage: test
  script:
    - cat ./app/.env

# listing-dir:
#   image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
#   script:
#     - aws eks list-clusters

# veryfing-env-file:
#   script:
#     - cat ./app/.env

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  environment: production
