name: Deploy to Kubernetes
on:
  push:
    branches:
      - master
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Teste
        run: echo ${{ github.event.head_commit.message }}

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::471112647960:role/GitHubAction-AssumeRoleWithAction #change to reflect your IAM role’s ARN
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: us-east-2

      - name: Sts GetCallerIdentity
        run: aws eks list-clusters

      - name: Configure kubectl
        run: mkdir -p ~/.kube && echo ${{ secrets.KUBECONFIG_FILE }}

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3

      # - name: Set up Docker
      #   uses: docker/setup-buildx-action@v3

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Build Docker image
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: .
      #     push: true
      #     tags: b2mplatform/b2m-track-processes:${{ github.event.head_commit.message }}

      # - name: Configure kubectl
      #   run: mkdir -p ~/.kube && mv k8s/kubeconfig.yaml ~/.kube/config

      # - uses: swdotcom/update-and-apply-kubernetes-configs@v1
      #   with:
      #     k8-config-file-paths: k8s/deployment.yaml
      #     replacement-method: list
      #     env-replacement-list: |
      #       IMAGE_TAG
      #   env:
      #     IMAGE_TAG: ${{ github.event.head_commit.message }}
